# Generated by Django 2.2.8 on 2020-03-04 10:00

from django.db import migrations, models
import django.db.models.deletion
import serverside.django.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users__actions',
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users__permissiongroups',
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('avatar', serverside.django.fields.S3Field(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('permission_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissiongroup_users', to='users.PermissionGroup')),
            ],
            options={
                'db_table': 'users__users',
                'ordering': ('-updated',),
            },
        ),
    ]
