# username/repository
id: asciialex/python-serverside

baseurl: ""

# name of the software
name: Python Serverside

# current version of the software
version: 1.0.2

# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

# extension of the favicon, blank to disable
favicon: png

# set this to true to replace the generated header navbar by _includes/navbar.html
customNavBar: false

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/asciialex/python-serverside

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/asciialex/python-serverside

# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# github buttons
githubButton:
  user: asciialex
  repo: python-serverside


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']
